name: Java CI with Maven, Docker Hub and Nexus

on:
  push:
    branches: [ "main", "meriemBH" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and SonarCloud Scan
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=ziedtuihri_PI_BackEnd -Dsonar.organization=ziedtuihri -DskipTests
        working-directory: ./pi
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_SECRET_TOKEN }}

      - name: Setup Maven settings.xml with Nexus credentials
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy JAR to Nexus
        run: mvn deploy -DskipTests
        working-directory: ./pi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t meriem01/pi-backend:latest ./pi

      - name: Push Docker image to Docker Hub
        run: docker push meriem01/pi-backend:latest
