name: Test Docker

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Docker info
        run: docker info

      - name: Create simple Dockerfile
        run: |
          echo -e "FROM alpine\nCMD echo Hello from Docker" > Dockerfile
          ls -la Dockerfile

      - name: Build Docker image
        run: docker build -t test-image:latest .

      - name: Run Docker image
        run: docker run test-image:latest
