name: Java CI with Maven and Docker Hub

on:
  push:
    branches: [ "meriemBH" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./pi

      - name: SonarCloud Scan
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=ziedtuihri_PI_BackEnd \
          -Dsonar.organization=ziedtuihri
        working-directory: ./pi
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_SECRET_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Nexus
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login f41d-102-104-219-38.ngrok-free.app --username ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t f41d-102-104-219-38.ngrok-free.app/repository/docker-hosted/pi-app:latest .
        working-directory: ./pi

      - name: Push Docker image
        run: docker push f41d-102-104-219-38.ngrok-free.app/repository/docker-hosted/pi-app:latest